using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Versioning;
using Microsoft.AspNetCore.Mvc.ApplicationParts;

[assembly: AssemblyCompany("Bd2.Server.Api")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0+25b884a69aa8db9a220cff57d9072b484d45c6a8")]
[assembly: AssemblyProduct("Bd2.Server.Api")]
[assembly: AssemblyTitle("Bd2.Server.Api")]
[assembly: ApplicationPart("Bd2.Server.Common")]
[assembly: ApplicationPart("Bd2.Server.Extensions")]
[assembly: ApplicationPart("Bd2.Server.iServices")]
[assembly: ApplicationPart("Bd2.Server.Services")]
[assembly: ApplicationPart("EasyTool.Core")]
[assembly: ApplicationPart("Swashbuckle.AspNetCore.SwaggerGen")]
[assembly: AssemblyVersion("1.0.0.0")]
