using Google.Protobuf.Reflection;

namespace Bd2.Server.Common.Proto.Net;

public enum Define_AchievementConditionType
{
	[OriginalName("ACHIEVE_NONE")]
	AchieveNone,
	[OriginalName("ACHIEVE_ITEM_TYPE_GET")]
	AchieveItemTypeGet,
	[OriginalName("ACHIEVE_ITEM_TYPE_USE")]
	AchieveItemTypeUse,
	[OriginalName("ACHIEVE_RESOURCE_GET")]
	AchieveResourceGet,
	[OriginalName("ACHIEVE_RESOURCE_USE")]
	AchieveResourceUse,
	[OriginalName("ACHIEVE_COLLECTION_QUEST_ITEM_GET")]
	AchieveCollectionQuestItemGet,
	[OriginalName("ACHIEVE_RECIPE_GET")]
	AchieveRecipeGet,
	[OriginalName("ACHIEVE_EQUIPMENT_GET")]
	AchieveEquipmentGet,
	[OriginalName("ACHIEVE_EQUIPMENT_BREAK")]
	AchieveEquipmentBreak,
	[OriginalName("ACHIEVE_EQUIPMENT_UPGRADE_SUCCESS")]
	AchieveEquipmentUpgradeSuccess,
	[OriginalName("ACHIEVE_EQUIPMENT_UPGRADE_FAIL")]
	AchieveEquipmentUpgradeFail,
	[OriginalName("ACHIEVE_EQUIPMENT_SMELTING_SUCCESS")]
	AchieveEquipmentSmeltingSuccess,
	[OriginalName("ACHIEVE_EQUIPMENT_SMELTING_FAIL")]
	AchieveEquipmentSmeltingFail,
	[OriginalName("ACHIEVE_COOKING")]
	AchieveCooking,
	[OriginalName("ACHIEVE_MAIN_QUEST_ALL_CLEAR_LEVEL_0")]
	AchieveMainQuestAllClearLevel0,
	[OriginalName("ACHIEVE_MAIN_QUEST_ALL_CLEAR_LEVEL_1")]
	AchieveMainQuestAllClearLevel1,
	[OriginalName("ACHIEVE_MAIN_QUEST_ALL_CLEAR_LEVEL_2")]
	AchieveMainQuestAllClearLevel2,
	[OriginalName("ACHIEVE_QUEST_CLEAR_DAILY")]
	AchieveQuestClearDaily,
	[OriginalName("ACHIEVE_QUEST_CLEAR_SUB")]
	AchieveQuestClearSub,
	[OriginalName("ACHIEVE_CHAR_GET")]
	AchieveCharGet,
	[OriginalName("ACHIEVE_CHAR_GRADE_GET")]
	AchieveCharGradeGet,
	[OriginalName("ACHIEVE_CHAR_CLASS_UP")]
	AchieveCharClassUp,
	[OriginalName("ACHIEVE_CHAR_LEVEL_UP")]
	AchieveCharLevelUp,
	[OriginalName("ACHIEVE_TALENT_SKILL_USE")]
	AchieveTalentSkillUse,
	[OriginalName("ACHIEVE_TALENT_UPGRADE")]
	AchieveTalentUpgrade,
	[OriginalName("ACHIEVE_TALENT_GRADE_GOAL")]
	AchieveTalentGradeGoal,
	[OriginalName("ACHIEVE_COSTUME_GET")]
	AchieveCostumeGet,
	[OriginalName("ACHIEVE_COSTUME_UPGRADE")]
	AchieveCostumeUpgrade,
	[OriginalName("ACHIEVE_FILED_OBJECT_REWARD_TYPE_1_GET")]
	AchieveFiledObjectRewardType1Get,
	[OriginalName("ACHIEVE_FILED_OBJECT_RESEARCH_REWARD_GET")]
	AchieveFiledObjectResearchRewardGet,
	[OriginalName("ACHIEVE_FILED_OBJECT_REWARD_TYPE_5_GET")]
	AchieveFiledObjectRewardType5Get,
	[OriginalName("ACHIEVE_FILED_OBJECT_REWARD_TYPE_2_GET")]
	AchieveFiledObjectRewardType2Get,
	[OriginalName("ACHIEVE_WAY_POINT_ACTIVE")]
	AchieveWayPointActive,
	[OriginalName("ACHIEVE_MAP_REWARD_ALL")]
	AchieveMapRewardAll,
	[OriginalName("ACHIEVE_MAP_REWARD_ALL_IN_PACK")]
	AchieveMapRewardAllInPack,
	[OriginalName("ACHIEVE_NPC_SHOP_BUY")]
	AchieveNpcShopBuy,
	[OriginalName("ACHIEVE_NPC_SHOP_SELL")]
	AchieveNpcShopSell,
	[OriginalName("ACHIEVE_PVP_BATTLE_WIN")]
	AchievePvpBattleWin,
	[OriginalName("ACHIEVE_PVP_BATTLE_LOSE")]
	AchievePvpBattleLose,
	[OriginalName("ACHIEVE_PVP_RANK_GOAL")]
	AchievePvpRankGoal,
	[OriginalName("ACHIEVE_CASH_SHOP_BUY")]
	AchieveCashShopBuy,
	[OriginalName("ACHIEVE_EVIL_CASTLE_RANK_GOAL_FLOOR_1")]
	AchieveEvilCastleRankGoalFloor1,
	[OriginalName("ACHIEVE_EVIL_CASTLE_CLEAR_ID")]
	AchieveEvilCastleClearId,
	[OriginalName("ACHIEVE_FIELD_MONSTER_BATTLE_WIN")]
	AchieveFieldMonsterBattleWin,
	[OriginalName("ACHIEVE_FIELD_MONSTER_BATTLE_LOSE")]
	AchieveFieldMonsterBattleLose,
	[OriginalName("ACHIEVE_FIELD_MONSTER_KILL")]
	AchieveFieldMonsterKill,
	[OriginalName("ACHIEVE_FILED_OBJECT_REWARD_TYPE_6_GET")]
	AchieveFiledObjectRewardType6Get,
	[OriginalName("ACHIEVE_HUNTING_GROUND_CLEAR_LEVEL_0")]
	AchieveHuntingGroundClearLevel0,
	[OriginalName("ACHIEVE_HUNTING_GROUND_CLEAR_LEVEL_1")]
	AchieveHuntingGroundClearLevel1,
	[OriginalName("ACHIEVE_HUNTING_GROUND_CLEAR_LEVEL_2")]
	AchieveHuntingGroundClearLevel2,
	[OriginalName("ACHIEVE_LOGIN")]
	AchieveLogin,
	[OriginalName("ACHIEVE_USER_ID_CHANGE")]
	AchieveUserIdChange,
	[OriginalName("ACHIEVE_PLATFORM_ACCOUNT_LINK")]
	AchievePlatformAccountLink,
	[OriginalName("ACHIEVE_DAILY_MISSION_ALL_CLEAR")]
	AchieveDailyMissionAllClear,
	[OriginalName("ACHIEVE_GACHA_BUY")]
	AchieveGachaBuy,
	[OriginalName("ACHIEVE_FOOD_EAT")]
	AchieveFoodEat,
	[OriginalName("ACHIEVE_BUFF_FOOD_EAT")]
	AchieveBuffFoodEat,
	[OriginalName("ACHIEVE_ITEM_INVEN_SLOT_ADD")]
	AchieveItemInvenSlotAdd,
	[OriginalName("ACHIEVE_EQUIPMENT_SLOT_ADD")]
	AchieveEquipmentSlotAdd,
	[OriginalName("ACHIEVE_ITEM_STORAGE_PUT")]
	AchieveItemStoragePut,
	[OriginalName("ACHIEVE_EQUIPMENT_STORAGE_PUT")]
	AchieveEquipmentStoragePut,
	[OriginalName("ACHIEVE_ITEM_STORAGE_INVEN_SLOT_ADD")]
	AchieveItemStorageInvenSlotAdd,
	[OriginalName("ACHIEVE_EQUIPMENT_STORAGE_SLOT_ADD")]
	AchieveEquipmentStorageSlotAdd,
	[OriginalName("ACHIEVE_FILED_MONSTER_DAMAGE")]
	AchieveFiledMonsterDamage,
	[OriginalName("ACHIEVE_FILED_MONSTER_REWARD")]
	AchieveFiledMonsterReward,
	[OriginalName("ACHIEVE_FILED_MONSTER_CRASH_MOVE")]
	AchieveFiledMonsterCrashMove,
	[OriginalName("ACHIEVE_NPC_TALK")]
	AchieveNpcTalk,
	[OriginalName("ACHIEVE_INN_USE")]
	AchieveInnUse,
	[OriginalName("ACHIEVE_REPUTATION_GOOD_GOAL")]
	AchieveReputationGoodGoal,
	[OriginalName("ACHIEVE_REPUTATION_BAD_GOAL")]
	AchieveReputationBadGoal,
	[OriginalName("ACHIEVE_ACHIEVEMENT_LEVEL_GOAL")]
	AchieveAchievementLevelGoal,
	[OriginalName("ACHIEVE_PORTRAIT_COSTUME_CHANGE")]
	AchievePortraitCostumeChange,
	[OriginalName("ACHIEVE_MAIN_QUEST_ALL_CLEAR_LEVEL_3")]
	AchieveMainQuestAllClearLevel3,
	[OriginalName("ACHIEVE_MAIN_QUEST_ALL_CLEAR_LEVEL_4")]
	AchieveMainQuestAllClearLevel4,
	[OriginalName("ACHIEVE_EVIL_CASTLE_RANK_GOAL_FLOOR_2")]
	AchieveEvilCastleRankGoalFloor2,
	[OriginalName("ACHIEVE_EVIL_CASTLE_RANK_GOAL_FLOOR_3")]
	AchieveEvilCastleRankGoalFloor3,
	[OriginalName("ACHIEVE_EVIL_CASTLE_RANK_GOAL_FLOOR_4")]
	AchieveEvilCastleRankGoalFloor4,
	[OriginalName("ACHIEVE_EVIL_CASTLE_RANK_GOAL_FLOOR_5")]
	AchieveEvilCastleRankGoalFloor5,
	[OriginalName("ACHIEVE_EVIL_CASTLE_RANK_GOAL_FLOOR_6")]
	AchieveEvilCastleRankGoalFloor6,
	[OriginalName("ACHIEVE_JEWELRY_GET")]
	AchieveJewelryGet,
	[OriginalName("ACHIEVE_JEWELRY_USE")]
	AchieveJewelryUse,
	[OriginalName("ACHIEVE_PVP_AP_USE")]
	AchievePvpApUse,
	[OriginalName("ACHIEVE_HUNTING_AP_USE")]
	AchieveHuntingApUse,
	[OriginalName("ACHIEVE_COSTUME_UPGRADE_TARGET_CHAR_GRADE")]
	AchieveCostumeUpgradeTargetCharGrade,
	[OriginalName("ACHIEVE_MONSTER_HUNT_BATTLE_END_COUNT")]
	AchieveMonsterHuntBattleEndCount,
	[OriginalName("ACHIEVE_MONSTER_HUNT_BATTLE_END_LEVEL")]
	AchieveMonsterHuntBattleEndLevel,
	[OriginalName("ACHIEVE_EQUIPMENT_PRIVATE_GET")]
	AchieveEquipmentPrivateGet,
	[OriginalName("ACHIEVE_EQUIPMENT_PRIVATE_UPGRADE_SUCCESS")]
	AchieveEquipmentPrivateUpgradeSuccess,
	[OriginalName("ACHIEVE_EVIL_CASTLE_GREED_TOWER_CLEAR")]
	AchieveEvilCastleGreedTowerClear,
	[OriginalName("ACHIEVE_EVIL_CASTLE_GREED_TOWER_ALL_CLEAR_BATTLE_CHALLENGE")]
	AchieveEvilCastleGreedTowerAllClearBattleChallenge,
	[OriginalName("ACHIEVE_EVIL_CASTLE_RANK_GOAL")]
	AchieveEvilCastleRankGoal,
	[OriginalName("ACHIEVE_MONSTER_HUNT_RANK_GOAL")]
	AchieveMonsterHuntRankGoal,
	[OriginalName("ACHIEVE_HAVE_RANK_TITLE")]
	AchieveHaveRankTitle,
	[OriginalName("ACHIEVE_GACHA_COSTUME_GRADE_5_GET_3")]
	AchieveGachaCostumeGrade5Get3,
	[OriginalName("ACHIEVE_GACHA_PRIVATE_UNIQUE_GRADE_4_GET_5")]
	AchieveGachaPrivateUniqueGrade4Get5,
	[OriginalName("ACHIEVE_TOTAL_WAR_DAMAGE")]
	AchieveTotalWarDamage,
	[OriginalName("ACHIEVE_TORCH_LIGHT_AP_USE")]
	AchieveTorchLightApUse,
	[OriginalName("ACHIEVE_TOTAL_WAR_BATTLE_END_COUNT")]
	AchieveTotalWarBattleEndCount,
	[OriginalName("ACHIEVE_COSTUME_POTENTIAL_ACTIVATION_SKILL_NODE")]
	AchieveCostumePotentialActivationSkillNode,
	[OriginalName("ACHIEVE_EVENT_STORY_CLEAR_TARGET_GROUP_ID")]
	AchieveEventStoryClearTargetGroupId,
	[OriginalName("ACHIEVE_GUILD_ATTENDANCE")]
	AchieveGuildAttendance,
	[OriginalName("ACHIEVE_GUILD_SUPPORTER_CHAR")]
	AchieveGuildSupporterChar,
	[OriginalName("ACHIEVE_EVIL_CASTLE_ROGUE_LIKE_CLEAR_COUNT")]
	AchieveEvilCastleRogueLikeClearCount,
	[OriginalName("ACHIEVE_EVIL_CASTLE_ROGUE_LIKE_SCORE")]
	AchieveEvilCastleRogueLikeScore,
	[OriginalName("ACHIEVE_EVIL_CASTLE_ROGUE_LIKE_RANK_GOAL")]
	AchieveEvilCastleRogueLikeRankGoal
}
